version: '3.4'

services:
  se161774.productmanagement.api:
    image: ${DOCKER_REGISTRY-}product-management-be
    build:
      context: .
      dockerfile: SE161774.ProductManagement.API/Dockerfile
    ports:
      - "9002:8080"
      - "9091:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
  #   depends_on:
  #     - sqldata
  # sqldata:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   environment:
  #     - MSSQL_SA_PASSWORD=vV5r9tn0M4@
  #     - ACCEPT_EULA=Y
  #   ports:
  #     - "1440:1433"  